### PR TITLE
set up scss compiling

### PR DESCRIPTION
**Pull request by dthai92**

### CODE REVIEW

**Comment by obber** [comment]
I would recommend git ignoring the compiled css! thoughts?

**Comment by dthai92** [comment]
Is there a specific advantage of git ignoring the compiled css (main.css)?

**Comment by obber** [comment]
Say I made a change in my source .scss file. I then compile it to test my code. Then, it checks out so I push the changes. Now, I've pushed the same set of changes, one inside of the actual source code before compilation (scss), as well a duplicate set on my distribution css files which only serves the purpose of serving up a functioning site. 

Ultimately, github is for source code, and pushing up compiled code can cause confusion.

**Comment by dthai92** [comment]
Ignoring sounds reasonable. I realized you can't use node-sass to compile the .scss into a main.css if the file already exists.

**Comment by obber** [comment]
Hmm, that doesn't seem right, shouldn't be able to overwrite it (compile again)?

But yeah, gitignoring for non-source code is generally a good idea so you don't push duplicate changes. The way I see it done in a lot of projects is that a dist/ (or public/dist) folder is gitignored, and all of the compiled code gets dumped into dist, so you don't have to gitignore individual files. I'll merge it though, you can update the gitignore as you need.

**Pull request merged**
